
// ===============================
// lib/main.dart
// ===============================
import 'package:flutter/material.dart';
import 'package:provider/provider.dart';
import 'package:supabase_flutter/supabase_flutter.dart';

import 'providers/auth_provider.dart';
import 'providers/settings_provider.dart';
import 'providers/wallet_provider.dart';
import 'providers/transactions_provider.dart';
import 'screens/login_screen.dart';
import 'screens/root_shell.dart';

Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();

  // TODO: Replace with your Supabase URL and anon key
  await Supabase.initialize(
    url: const String.fromEnvironment('SUPABASE_URL', defaultValue: 'https://tffsmkjsmjpnhqvfeypa.supabase.co'),
    anonKey: const String.fromEnvironment('SUPABASE_ANON_KEY', defaultValue: 'sb_secret_bBjOr7P3zZDDrTNsFH-uhQ_O16DNSq9'),
  );

  runApp(const CardtonicsApp());
}

class CardtonicsApp extends StatelessWidget {
  const CardtonicsApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MultiProvider(
      providers: [
        ChangeNotifierProvider(create: (_) => SettingsProvider()..load()),
        ChangeNotifierProvider(create: (_) => AuthProvider()..bootstrap()),
        ChangeNotifierProvider(create: (_) => WalletProvider()..bootstrap()),
        ChangeNotifierProvider(create: (_) => TransactionsProvider()..bootstrap()),
      ],
      child: Consumer<SettingsProvider>(
        builder: (context, settings, _) {
          return MaterialApp(
            title: 'Cardtonics',
            debugShowCheckedModeBanner: false,
            theme: ThemeData(
              colorScheme: ColorScheme.fromSeed(seedColor: const Color(0xFF0F9AFE)),
              useMaterial3: true,
              scaffoldBackgroundColor: const Color(0xFFF7F8FB),
              appBarTheme: const AppBarTheme(centerTitle: false),
            ),
            home: const Bootstrapper(),
          );
        },
      ),
    );
  }
}

/// Decides whether to show Login or the App shell
class Bootstrapper extends StatelessWidget {
  const Bootstrapper({super.key});
  @override
  Widget build(BuildContext context) {
    return Consumer<AuthProvider>(
      builder: (context, auth, _) {
        if (auth.isBooting) {
          return const Scaffold(
            body: Center(child: CircularProgressIndicator()),
          );
        }
        return auth.isAuthenticated ? const RootShell() : const LoginScreen();
      },
    );
  }
}



// Supabase quick schema todo
// ===============================
/*
-- auth handled by Supabase Auth (email/password)

-- wallets
create table if not exists wallets (
  user_id uuid primary key references auth.users(id) on delete cascade,
  balance numeric default 0
);

-- helper function (RPC) to get current user's balance
create or replace function get_wallet_balance()
returns table(balance numeric)
language sql security definer set search_path = public as $$
  select coalesce(balance, 0) as balance from wallets where user_id = auth.uid();
$$;

-- bank accounts
create table if not exists bank_accounts (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) on delete cascade,
  bank_name text,
  account_number text,
  account_name text,
  created_at timestamp default now()
);

-- transactions
create table if not exists transactions (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) on delete cascade,
  type text check (type in ('all','billPayment','buyGiftCard','justGadgets','sellGiftCard','rewardPoints','walletTopUp','withdrawal','virtualCard')),
  amount numeric,
  note text,
  created_at timestamp default now()
);

-- RLS policies
alter table wallets enable row level security;
create policy "wallets select own" on wallets for select using (user_id = auth.uid());

alter table bank_accounts enable row level security;
create policy "bank sel" on bank_accounts for select using (user_id = auth.uid());
create policy "bank ins" on bank_accounts for insert with check (user_id = auth.uid());

alter table transactions enable row level security;
create policy "tx sel" on transactions for select using (user_id = auth.uid());
*/
